version: '3.8'
services:
  zoo1:
    image: 'zookeeper:3.6.4'
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    volumes:
      - ./data/zookeeper:/data
      - ./datalog/zookeeper:/datalog
    networks:
      - ranger-net

networks:
  ranger-net:
    name: rangernw
    external: true
