#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3.8'
services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/etc/trino
      - ./conf/core-site.xml:/etc/hadoop/conf/core-site.xml:ro
      - ./conf/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml:ro
    networks:
      - shared-network

  spark-master:
    image: 'apache/spark:3.5.0'
    working_dir: /opt/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    ports:
      - "9090:9090"  # Spark master UI
      - "7077:7077"  # Spark master communication port
    environment:
      - SPARK_LOCAL_IP=spark-master
    volumes:
      - ./conf/spark/hive-jars:/opt/spark/hive-jars
      - ./conf/spark/spark-events:/opt/spark/spark-events
      - ./conf/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
      - ./conf/spark/hive-site.xml:/opt/spark/conf/hive-site.xml:ro
      - ./conf/spark/ranger-hive-audit.xml:/opt/spark/conf/ranger-hive-audit.xml:ro
      - ./conf/spark/ranger-hive-security.xml:/opt/spark/conf/ranger-hive-security.xml:ro
      - ./conf/spark/ranger-policymgr-ssl.xml:/opt/spark/conf/ranger-policymgr-ssl.xml:ro
      - ./conf/core-site.xml:/opt/spark/conf/core-site.xml:ro
      - ./conf/hdfs-site.xml:/opt/spark/conf/hdfs-site.xml:ro
    networks:
      - ranger-net
      - shared-network

  spark-worker:
    image: 'apache/spark:3.5.0'
    working_dir: /opt/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_CORES=1  # Number of cores to use on each worker
      - SPARK_WORKER_MEMORY=1g  # Amount of memory to use on each worker
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_LOCAL_IP=spark-worker
    volumes:
      - ./conf/spark/hive-jars:/opt/spark/hive-jars
      - ./conf/spark/spark-events:/opt/spark/spark-events
      - ./conf/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
      - ./conf/spark/hive-site.xml:/opt/spark/conf/hive-site.xml:ro
      - ./conf/spark/ranger-hive-audit.xml:/opt/spark/conf/ranger-hive-audit.xml:ro
      - ./conf/spark/ranger-hive-security.xml:/opt/spark/conf/ranger-hive-security.xml:ro
      - ./conf/spark/ranger-policymgr-ssl.xml:/opt/spark/conf/ranger-policymgr-ssl.xml:ro
      - ./conf/core-site.xml:/opt/spark/conf/core-site.xml:ro
      - ./conf/hdfs-site.xml:/opt/spark/conf/hdfs-site.xml:ro
    networks:
      - ranger-net
      - shared-network

networks:
  ranger-net:
    name: rangernw
    external: true
  shared-network:
    external: true