version: "3.8"

x-common-config:
  &common-config
  image: apache/hadoop:3.3.6
  volumes:
    - ../conf/ranger-hdfs-audit.xml:/opt/hadoop/etc/hadoop/ranger-hdfs-audit.xml
    - ../conf/ranger-hdfs-security.xml:/opt/hadoop/etc/hadoop/ranger-hdfs-security.xml
    - ../conf/ranger-policymgr-ssl.xml:/opt/hadoop/etc/hadoop/ranger-policymgr-ssl.xml
    - ../conf/ranger-jars:/opt/hadoop/share/hadoop/hdfs/lib
    - ./test.csv:/opt/hadoop/test.csv
    - ./load_test_data/10/eshop_sales_10.csv:/opt/hadoop/eshop_sales_10.csv
    - ./load_test_data/10/restaurant_orders_10.csv:/opt/hadoop/restaurant_orders_10.csv
    - ./load_test_data/10/stock_trades_10.csv:/opt/hadoop/stock_trades_10.csv
    - ./load_test_data/50/eshop_sales_50.csv:/opt/hadoop/eshop_sales_50.csv
    - ./load_test_data/50/restaurant_orders_50.csv:/opt/hadoop/restaurant_orders_50.csv
    - ./load_test_data/50/stock_trades_50.csv:/opt/hadoop/stock_trades_50.csv
    - ./load_test_data/500/eshop_sales_500.csv:/opt/hadoop/eshop_sales_500.csv
    - ./load_test_data/500/restaurant_orders_500.csv:/opt/hadoop/restaurant_orders_500.csv
    - ./load_test_data/500/stock_trades_500.csv:/opt/hadoop/stock_trades_500.csv
  env_file:
    - ./config
  networks:
    - ranger-net

services:
  namenode:
    <<: *common-config
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
  datanode:
    <<: *common-config
    command: ["hdfs", "datanode"]
  resourcemanager:
    <<: *common-config
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
  nodemanager:
    <<: *common-config
    command: ["yarn", "nodemanager"]

networks:
  ranger-net:
    name: rangernw
    external: true
