version: "3.8"

x-common-config:
  &common-config
  image: apache/hadoop:3.3.6
  volumes:
    - ../conf/ranger-hdfs-audit.xml:/opt/hadoop/etc/hadoop/ranger-hdfs-audit.xml
    - ../conf/ranger-hdfs-security.xml:/opt/hadoop/etc/hadoop/ranger-hdfs-security.xml
    - ../conf/ranger-policymgr-ssl.xml:/opt/hadoop/etc/hadoop/ranger-policymgr-ssl.xml
    - ../conf/ranger-jars/ranger-hdfs-plugin-2.4.1-SNAPSHOT.jar:/opt/hadoop/share/hadoop/hdfs/lib/ranger-hdfs-plugin-2.4.1-SNAPSHOT.jar
    - ../conf/ranger-jars/ranger-kms-plugin-2.4.1-SNAPSHOT.jar:/opt/hadoop/share/hadoop/hdfs/lib/ranger-kms-plugin-2.4.1-SNAPSHOT.jar
    - ../conf/ranger-jars/ranger-plugins-audit-2.4.1-SNAPSHOT.jar:/opt/hadoop/share/hadoop/hdfs/lib/ranger-plugins-audit-2.4.1-SNAPSHOT.jar
    - ../conf/ranger-jars/ranger-plugins-common-2.4.1-SNAPSHOT-jar-with-dependencies.jar:/opt/hadoop/share/hadoop/hdfs/lib/ranger-plugins-common-2.4.1-SNAPSHOT-jar-with-dependencies.jar
    - ./test.csv:/opt/hadoop/test.csv
  env_file:
    - ./config
  networks:
    - ranger-net

services:
  namenode:
    <<: *common-config
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
      - 7007:7007
    environment:
      HADOOP_HOME: "/opt/hadoop"
      HADOOP_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7007"
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
  datanode:
    <<: *common-config
    command: ["hdfs", "datanode"]
  resourcemanager:
    <<: *common-config
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
  nodemanager:
    <<: *common-config
    command: ["yarn", "nodemanager"]

networks:
  ranger-net:
    name: rangernw
    external: true
